"""Reference snapshot of every verified_sources record, including inactive sources.

Synchronized from the database on 2026-10-03 (Asia/Dhaka), without modifying
that table. Runtime source resolution continues to use SourceRepository.
Domain keys map to canonical_name; name maps to display_name. Nullable values
and ordered arrays are preserved exactly. SOURCE_RECORD_METADATA records the
original IDs and timestamps for documentation; it is not runtime seed input.
Never run the seed script to synchronize this file back into the live database.
"""
from typing import TypedDict


class SourceConfig(TypedDict, total=False):
    name: str
    display_name_en: str | None
    base_url: str
    aliases: list[str] | None
    body_selectors: list[str] | None
    title_selectors: list[str] | None
    date_selectors: list[str] | None
    internal_search_url: str | None
    article_url_patterns: list[str] | None
    rss_url: str | None
    js_rendered: bool
    search_language: str
    language: str
    is_active: bool
    description: str | None


SOURCE_REGISTRY: dict[str, SourceConfig] = {'bangla.thedailystar.net': {'aliases': ['bangla.thedailystar.net',
                                         'daily star',
                                         'dailystar',
                                         'the daily star',
                                         'the daily star bangla',
                                         'thedailystar',
                                         'দ্য ডেইলি স্টার'],
                             'base_url': 'https://bangla.thedailystar.net',
                             'rss_url': None,
                             'language': 'bn',
                             'is_active': True,
                             'description': 'Bangladeshi Bangla-language news outlet: The Daily '
                                            'Star Bangla',
                             'body_selectors': ['.block-field-blocknodenewsbody p',
                                                '.article-body p',
                                                '.text-formatted p',
                                                'article p'],
                             'title_selectors': ['.block-field-blocknodenewstitle h1',
                                                 'h1.mb-[20px]',
                                                 'h1.title',
                                                 'h1'],
                             'date_selectors': ['.date',
                                                '.card-info',
                                                "[class*='date']",
                                                '.published-time',
                                                'time[datetime]',
                                                'time'],
                             'internal_search_url': None,
                             'article_url_patterns': ['bangla\\.thedailystar\\.net/[a-zA-Z0-9-]+/.*news-\\d+',
                                                      'bangla\\.thedailystar\\.net/node/\\d+'],
                             'display_name_en': None,
                             'search_language': 'bn',
                             'js_rendered': False,
                             'name': 'দ্য ডেইলি স্টার'},
 'bd-pratidin.com': {'aliases': ['bangladesh pratidin',
                                 'bd pratidin',
                                 'bd-pratidin',
                                 'bd-pratidin.com',
                                 'www.bd-pratidin.com',
                                 'বাংলাদেশ প্রতিদিন'],
                     'base_url': 'https://www.bd-pratidin.com',
                     'rss_url': 'https://www.bd-pratidin.com/feed',
                     'language': 'bn',
                     'is_active': True,
                     'description': 'Bangladeshi Bangla-language news outlet: Bangladesh Pratidin',
                     'body_selectors': ['.news-details p',
                                        '#news-details p',
                                        "div[class*='news-details'] p",
                                        'article .news-body p',
                                        '.details-content p',
                                        '.post-content p',
                                        'article p'],
                     'title_selectors': ['h1.news-title',
                                         'div.news-title h1',
                                         '.news-heading h1',
                                         "h1[class*='title']",
                                         'h1'],
                     'date_selectors': ['.post-date time',
                                        '.post-date',
                                        '.date',
                                        'time[datetime]',
                                        "span[class*='date']",
                                        'time'],
                     'internal_search_url': 'https://www.bd-pratidin.com/search?q={query}',
                     'article_url_patterns': ['bd-pratidin\\.com/[^/]+/\\d{4}/\\d{2}/\\d{2}/\\d+',
                                              'bd-pratidin\\.com/[^/]+/\\d{6,}',
                                              'bd-pratidin\\.com/\\d{6,}$'],
                     'display_name_en': None,
                     'search_language': 'bn',
                     'js_rendered': False,
                     'name': 'বাংলাদেশ প্রতিদিন'},
 'dailyinqilab.com': {'aliases': ['daily inqilab',
                                  'dailyinqilab',
                                  'dailyinqilab.com',
                                  'inqilab',
                                  'www.dailyinqilab.com',
                                  'ইনকিলাব'],
                      'base_url': 'https://dailyinqilab.com',
                      'rss_url': None,
                      'language': 'bn',
                      'is_active': True,
                      'description': 'Bangladeshi Bangla-language news outlet: Daily Inqilab',
                      'body_selectors': ['.news-details p',
                                         "div[class*='news-details'] p",
                                         '.content p',
                                         'article .news-body p',
                                         'article p'],
                      'title_selectors': ['h1.title', "h1[class*='title']", 'h1'],
                      'date_selectors': ['.date', 'time[datetime]', "span[class*='date']", 'time'],
                      'internal_search_url': None,
                      'article_url_patterns': ['dailyinqilab\\.com/[^/]+/news/\\d+',
                                               'dailyinqilab\\.com/article/\\d+',
                                               'dailyinqilab\\.com/news/\\d+'],
                      'display_name_en': None,
                      'search_language': 'bn',
                      'js_rendered': False,
                      'name': 'ইনকিলাব'},
 'dailynayadiganta.com': {'aliases': ['daily nayadiganta',
                                      'dailynayadiganta.com',
                                      'naya diganta',
                                      'nayadiganta',
                                      'www.dailynayadiganta.com',
                                      'নয়া দিগন্ত'],
                          'base_url': 'https://www.dailynayadiganta.com',
                          'rss_url': None,
                          'language': 'bn',
                          'is_active': True,
                          'description': 'Bangladeshi Bangla-language news outlet: Naya Diganta',
                          'body_selectors': ['.news-content p',
                                             "div[class*='news-content'] p",
                                             '.content-details p',
                                             "div[class*='content-details'] p",
                                             "div[class*='news-body'] p",
                                             'article p'],
                          'title_selectors': ['h1.news-title',
                                              "h1[class*='news-title']",
                                              "h1[class*='title']",
                                              'h1'],
                          'date_selectors': ['.date',
                                             'time[datetime]',
                                             "span[class*='date']",
                                             'time'],
                          'internal_search_url': None,
                          'article_url_patterns': ['dailynayadiganta\\.com/post/[a-z0-9-]+/\\d+',
                                                   'dailynayadiganta\\.com/detail/news/\\d+'],
                          'display_name_en': None,
                          'search_language': 'bn',
                          'js_rendered': False,
                          'name': 'নয়া দিগন্ত'},
 'ittefaq.com.bd': {'aliases': ['ittefaq', 'ittefaq.com.bd', 'www.ittefaq.com.bd', 'ইত্তেফাক'],
                    'base_url': 'https://www.ittefaq.com.bd',
                    'rss_url': None,
                    'language': 'bn',
                    'is_active': True,
                    'description': 'Bangladeshi Bangla-language news outlet: Ittefaq',
                    'body_selectors': ['div.dtl_content_block p',
                                       'div.dtl_content_block',
                                       '.jw_article_body p',
                                       '.jw_article_body',
                                       '.details-content p',
                                       '.content-details p',
                                       'article p'],
                    'title_selectors': ['h1.title',
                                        "h1[class*='title']",
                                        '.jw_article_header h1',
                                        'h1'],
                    'date_selectors': ['.date', 'time[datetime]', "span[class*='date']", 'time'],
                    'internal_search_url': 'https://www.ittefaq.com.bd/search?q={query}',
                    'article_url_patterns': ['ittefaq\\.com\\.bd/\\d{5,}(?:/|$)',
                                             'ittefaq\\.com\\.bd/[a-z-]+/\\d{4}-\\d{2}-\\d{2}/\\d+',
                                             'ittefaq\\.com\\.bd/[a-z-]+/\\d+'],
                    'display_name_en': None,
                    'search_language': 'bn',
                    'js_rendered': False,
                    'name': 'ইত্তেফাক'},
 'jugantor.com': {'aliases': ['jugantor', 'jugantor.com', 'www.jugantor.com', 'যুগান্তর'],
                  'base_url': 'https://www.jugantor.com',
                  'rss_url': 'https://www.jugantor.com/feed',
                  'language': 'bn',
                  'is_active': True,
                  'description': 'Bangladeshi Bangla-language news outlet: Jugantor',
                  'body_selectors': ['.detailBody p',
                                     'div#myText p',
                                     '#myText',
                                     "div[id='myText'] p",
                                     '.news-details p',
                                     '.content-details p',
                                     "div[class*='news-body'] p",
                                     'article p'],
                  'title_selectors': ['h3.font-weight-bolder',
                                      'h1.news-title',
                                      "h1[class*='title']",
                                      'h1'],
                  'date_selectors': ['.post-date',
                                     '.date',
                                     'time[datetime]',
                                     "span[class*='date']",
                                     'time'],
                  'internal_search_url': None,
                  'article_url_patterns': ['jugantor\\.com/[^/]+/\\d{4}/\\d{2}/\\d{2}/\\d+',
                                           'jugantor\\.com/[^/]+/\\d{6,}$'],
                  'display_name_en': None,
                  'search_language': 'bn',
                  'js_rendered': False,
                  'name': 'যুগান্তর'},
 'kalerkantho.com': {'aliases': ['kaler kantho',
                                 'kalerkantho',
                                 'kalerkantho.com',
                                 'www.kalerkantho.com',
                                 'কালের কণ্ঠ'],
                     'base_url': 'https://www.kalerkantho.com',
                     'rss_url': 'https://www.kalerkantho.com/rss.xml',
                     'language': 'bn',
                     'is_active': True,
                     'description': 'Bangladeshi Bangla-language news outlet: Kaler Kantho',
                     'body_selectors': ['.details-txt p',
                                        'div.details-txt p',
                                        "div[class*='details-txt'] p",
                                        '.news-body p',
                                        '.news-details p',
                                        'article .details-body p',
                                        'article p'],
                     'title_selectors': ['h1.detail-title',
                                         "h1[class*='detail-title']",
                                         'h2.news-title',
                                         "h1[class*='title']",
                                         'h1'],
                     'date_selectors': ['.date-time',
                                        'span.date-time',
                                        '.date',
                                        'time[datetime]',
                                        "span[class*='date']",
                                        'time'],
                     'internal_search_url': None,
                     'article_url_patterns': ['kalerkantho\\.com/online/[^/]+/\\d{4}/\\d{2}/\\d{2}/\\d+',
                                              'kalerkantho\\.com/print-edition/[^/]+/\\d{4}/\\d{2}/\\d{2}/\\d+',
                                              'kalerkantho\\.com/[^/]+/[^/]+/\\d{4}/\\d{2}/\\d{2}/\\d+',
                                              'kalerkantho\\.com/[^/]+/\\d{4}/\\d{2}/\\d{2}/\\d+'],
                     'display_name_en': None,
                     'search_language': 'bn',
                     'js_rendered': False,
                     'name': 'কালের কণ্ঠ'},
 'mzamin.com': {'aliases': ['manab zamin',
                            'manabzamin',
                            'manabzamin.com',
                            'mzamin',
                            'mzamin.com',
                            'www.mzamin.com',
                            'মানবজমিন'],
                'base_url': 'https://mzamin.com',
                'rss_url': None,
                'language': 'bn',
                'is_active': True,
                'description': 'Bangladeshi Bangla-language news outlet: Manab Zamin',
                'body_selectors': ['#articleContent p',
                                   '#articleContent',
                                   '.prose p',
                                   '.details-text p',
                                   'div.details-text p',
                                   '.news-details p',
                                   '.col-md-8 .content p',
                                   '.col-md-8 p',
                                   'article p'],
                'title_selectors': ['h1.title', 'h2.title', "h1[class*='title']", 'h1'],
                'date_selectors': ['.date', 'time[datetime]', "span[class*='date']", 'time'],
                'internal_search_url': None,
                'article_url_patterns': ['mzamin\\.com/article/\\d+',
                                         'mzamin\\.com/article\\.php\\?mzamin=\\d+',
                                         'mzamin\\.com/news/\\d+'],
                'display_name_en': None,
                'search_language': 'bn',
                'js_rendered': False,
                'name': 'মানবজমিন'},
 'prothomalo.com': {'aliases': ['prothom alo',
                                'prothom-alo',
                                'prothomalo',
                                'prothomalo.com',
                                'www.prothomalo.com',
                                'প্রথম আলো'],
                    'base_url': 'https://www.prothomalo.com',
                    'rss_url': 'https://www.prothomalo.com/feed',
                    'language': 'bn',
                    'is_active': True,
                    'description': 'Bangladeshi Bangla-language news outlet: Prothom Alo',
                    'body_selectors': ['div.story-element-text',
                                       "div[class*='story-element-text']",
                                       "[data-component='Text'] p",
                                       '.story-element p',
                                       "div[class*='ArticleBody'] p",
                                       "div[class*='article-body'] p",
                                       '.story-content p',
                                       'article .content p',
                                       '.detail-content p',
                                       'article p'],
                    'title_selectors': ['h1.title',
                                        "h1[class*='story-title']",
                                        "h1[class*='title']",
                                        'h1'],
                    'date_selectors': ['time[datetime]',
                                       "[class*='published-time']",
                                       "[class*='PublishedTime']",
                                       '.time',
                                       'time'],
                    'internal_search_url': 'https://www.prothomalo.com/search?q={query}',
                    'article_url_patterns': ['prothomalo\\.com/[^/]+/[^/]*/article/[a-zA-Z0-9_-]+',
                                             'prothomalo\\.com/[^/]+/article/[a-zA-Z0-9_-]+',
                                             'prothomalo\\.com/[^/]+/[^/]+/[^/?#]{10,}',
                                             'prothomalo\\.com/[^/]+/[^/?#]{10,}'],
                    'display_name_en': None,
                    'search_language': 'bn',
                    'js_rendered': False,
                    'name': 'প্রথম আলো'},
 'samakal.com': {'aliases': ['samakal', 'samakal.com', 'www.samakal.com', 'সমকাল'],
                 'base_url': 'https://samakal.com',
                 'rss_url': 'https://samakal.com/feed',
                 'language': 'bn',
                 'is_active': True,
                 'description': 'Bangladeshi Bangla-language news outlet: Samakal',
                 'body_selectors': ['div.description p',
                                    "div[class*='description'] p",
                                    'div.detail-content p',
                                    '.news-content p',
                                    '.article-body p',
                                    'article p'],
                 'title_selectors': ['h1.detail-title',
                                     "h1[class*='detail-title']",
                                     "h1[class*='title']",
                                     'h1'],
                 'date_selectors': ['.date',
                                    '.post-date',
                                    'time[datetime]',
                                    "span[class*='date']",
                                    'time'],
                 'internal_search_url': None,
                 'article_url_patterns': ['samakal\\.com/[^/]+/article/\\d+',
                                          'samakal\\.com/[^/]+/article/[a-zA-Z0-9_-]+'],
                 'display_name_en': None,
                 'search_language': 'bn',
                 'js_rendered': False,
                 'name': 'সমকাল'}}

SOURCE_RECORD_METADATA: dict[str, dict[str, str]] = {'bangla.thedailystar.net': {'id': '8998cdf2-b38f-4ca1-91c2-37b2f342de70',
                             'created_at': '2026-07-07T21:23:05.369586+06:00',
                             'updated_at': '2026-08-01T15:09:11.848407+06:00'},
 'bd-pratidin.com': {'id': '8c0ea077-5a49-4443-9111-2784fed4f730',
                     'created_at': '2026-07-07T21:23:05.369586+06:00',
                     'updated_at': '2026-10-02T08:54:03.786146+06:00'},
 'dailyinqilab.com': {'id': '1d414b95-04ec-4b88-9fc5-779c83093f48',
                      'created_at': '2026-07-07T21:23:05.369586+06:00',
                      'updated_at': '2026-08-01T15:09:11.849804+06:00'},
 'dailynayadiganta.com': {'id': '867c5326-bbe1-46b7-a090-9ddd323ace1d',
                          'created_at': '2026-07-07T21:23:05.369586+06:00',
                          'updated_at': '2026-08-01T15:09:11.850125+06:00'},
 'ittefaq.com.bd': {'id': '341a3458-f89d-418e-9a9f-6351241192e9',
                    'created_at': '2026-07-07T21:23:05.369586+06:00',
                    'updated_at': '2026-08-01T15:09:11.849235+06:00'},
 'jugantor.com': {'id': '47e7fa15-6a3c-4d4f-b50b-6e08db5f255e',
                  'created_at': '2026-07-07T21:23:05.369586+06:00',
                  'updated_at': '2026-08-01T15:09:11.847675+06:00'},
 'kalerkantho.com': {'id': 'ee698838-47c6-47cf-ad51-258090a5d3db',
                     'created_at': '2026-07-07T21:23:05.369586+06:00',
                     'updated_at': '2026-08-01T15:09:11.846928+06:00'},
 'mzamin.com': {'id': '5f60fe94-65a2-4d69-87a1-3304c7054502',
                'created_at': '2026-07-07T21:23:05.369586+06:00',
                'updated_at': '2026-08-01T15:09:11.838193+06:00'},
 'prothomalo.com': {'id': '59c665d1-372f-42f4-b8e5-ba94d30299e9',
                    'created_at': '2026-07-07T21:23:05.369586+06:00',
                    'updated_at': '2026-07-07T21:23:05.369586+06:00'},
 'samakal.com': {'id': 'f16a1700-60d1-4954-8067-3c1636fae70b',
                 'created_at': '2026-07-07T21:23:05.369586+06:00',
                 'updated_at': '2026-07-07T21:23:05.369586+06:00'}}
