from pathlib import Path
root=Path('frontend/src')
p=root/'styles.scss'
s=p.read_text(encoding='utf-8-sig'); p.write_text("@use './app/shared/styles/verification-workspace';\n"+s,encoding='utf-8')
nav='''<nav class="method-nav" aria-label="Verification method"><a routerLink="/verify" NEWS>News text</a><a routerLink="/photo-card" PHOTO>Photocard</a><a routerLink="/multimodal" MULTI>Text &amp; image</a></nav>'''
def navigation(current):
    return nav.replace(current,'aria-current="page"').replace(' NEWS','').replace(' PHOTO','').replace(' MULTI','')
def header(kicker,title,description,current):
    return '<div class="verification-shell"><div class="flow-container"><header class="flow-heading"><div><span class="eyebrow">'+kicker+'</span><h1>'+title+'</h1><p>'+description+'</p></div><a routerLink="/dashboard" class="btn btn-ghost">Explore fact checks ↗</a></header>'+navigation(current)
# News input controls and bindings are preserved.
p=root/'app/features/verification/verify-claim/verify-claim.html'
s=p.read_text(encoding='utf-8-sig'); form=s[s.index('<form '):s.index('</form>')+7]
form=form.replace('<form [formGroup]="form" (ngSubmit)="onSubmit()">','<form [formGroup]="form" (ngSubmit)="onSubmit()"><fieldset [disabled]="loading || !!pendingSubmissionId">').replace('</form>','</fieldset></form>')
form=form.replace('Only active verified sources can be checked against.','Choose the outlet the claim says published this news.').replace('Select a verified news source','Select the claimed news outlet').replace('Verify Claim','Verify news').replace('News Headline (in Bangla)','Bengali headline').replace('Claimed Source','Claimed news outlet').replace('Publication Date','Claimed publication date')
out=header('CHECK A CLAIM','Check the news. Find the source.','Compare a Bengali headline with the news outlet it claims to come from. Add the article text and date if you have them.','NEWS')
out+='''@if (!result && !pendingSubmissionId) {<div class="flow-grid"><section class="surface"><div class="section-heading"><span class="eyebrow">01 / NEWS DETAILS</span><h2>What would you like to check?</h2><p>Fields marked * are required. Keep the original wording of the claim.</p></div>'''+form+'''
@if (error) {<div class="note warning" role="alert"><strong>Verification could not be completed</strong><p>{{ error }}</p><p>No verdict was reached. Your input is still here; you can submit it again.</p><button type="button" class="btn btn-secondary" (click)="onSubmit()">Try again</button></div>}
</section><aside class="side-stack"><section class="surface"><span class="eyebrow">YOUR CLAIM / PREVIEW</span>@if (form.value.headline) {<h2 class="claim-preview">{{ form.value.headline }}</h2>} @else {<p class="preview-placeholder">The headline you enter will appear here.</p>}<dl class="meta-grid"><div><dt>Claimed outlet</dt><dd>{{ form.value.claimed_source_text || 'Not selected' }}</dd></div><div><dt>Comparison scope</dt><dd>{{ form.value.body_text?.trim() ? 'Headline and article text' : 'Headline only' }}</dd></div></dl>@if (form.value.body_text) {<details><summary>Preview article text</summary><p class="preview-body">{{ form.value.body_text }}</p></details>}</section><section class="context-panel"><h2>What happens next</h2><ol class="guide-list"><li><strong>Find the original report</strong><p>We search the outlet you select for a corresponding story.</p></li><li><strong>Compare the claim</strong><p>Source, content and date findings are kept separate.</p></li><li><strong>Read the evidence</strong><p>Preliminary findings are available before expert review. A missing report alone does not make a claim false.</p></li></ol></section></aside></div>}
@if (pendingSubmissionId && !result) {<section class="surface state-card" role="status"><span class="eyebrow">CLAIM RECEIVED</span><div class="spinner"></div><h2>Verification in progress</h2><p class="claim-preview">{{ pendingHeadline }}</p><p>We are checking the claim against the selected news outlet. This page will update when the findings are ready.</p><div class="note"><strong>You can leave this page.</strong><p>The check continues in the background. Keep the result link to return later. Signed-in users can also find it in My submissions.</p></div><div class="actions"><a class="btn btn-primary" [routerLink]="['/verify', pendingSubmissionId]">View progress</a><a routerLink="/history" class="btn btn-secondary">My submissions</a></div></section>}
@if (result && !error) {<section class="flow-result"><div class="report-toolbar"><div><span class="eyebrow">YOUR VERIFICATION</span><h2>Verification result</h2></div><div class="actions"><a class="btn btn-secondary" [routerLink]="['/verify',result.submission_id]">Open full report ↗</a><button class="btn btn-ghost" (click)="reset()">Check another claim</button></div></div><section class="surface"><span class="eyebrow">SUBMITTED CLAIM</span><h2 class="claim-preview">{{ pendingHeadline || form.value.headline }}</h2></section>@if (servedFromCache) {<div class="note">This claim was checked before. Its saved result is shown. Choose “Check again for updated evidence” when submitting to request a fresh check.</div>}<app-verification-report [r]="result" /></section>}
</div></div>'''
p.write_text(out,encoding='utf-8'); p.with_suffix('.scss').write_text(':host { display: block; }\n',encoding='utf-8')
# Photocard keeps the existing uploader, fields and accepted lifecycle.
p=root/'app/features/photocard/photocard.html'; s=p.read_text(encoding='utf-8-sig')
controls=s[s.index('<div class="dropzone"'):s.index('<div class="hint-list">')]
controls=controls.replace('Publication date','Claimed publication date').replace('Claimed source','Claimed news outlet').replace('class="alert alert-error"','class="note warning" role="alert"')
out=header('CHECK A PHOTOCARD','Look beyond the image.','Upload a Bengali news photocard or screenshot and select the outlet it claims to come from. We will read its headline and look for the source report.','PHOTO')
out+='''@if (step === 'upload') {<div class="flow-grid"><section class="surface"><div class="section-heading"><span class="eyebrow">01 / IMAGE &amp; CONTEXT</span><h2>Add the photocard</h2><p>Keep the full headline visible. Fields marked * are required.</p></div><fieldset [disabled]="verifying">'''+controls+'''</fieldset></section><aside class="side-stack"><section class="surface"><span class="eyebrow">YOUR IMAGE / PREVIEW</span>@if (previewUrl) {<img [src]="previewUrl" class="preview-image" alt="Selected photocard preview"><dl class="meta-grid"><div><dt>Claimed outlet</dt><dd>{{ claimedSourceName() || 'Not selected' }}</dd></div><div><dt>Claimed date</dt><dd>{{ publishedDate || 'Not provided' }}</dd></div></dl>} @else {<p class="preview-placeholder">Your selected image will appear here before you submit it.</p>}<div class="note">Only the headline read from this card is compared with your selected outlet. This does not verify every visual element in the image.</div></section><section class="context-panel"><h2>A clearer image helps</h2><ol class="guide-list"><li><strong>Include the full headline</strong><p>A sharp, uncropped image is easier to read.</p></li><li><strong>Select the claimed outlet</strong><p>Choose the outlet named on the card. Do not choose where you found the screenshot.</p></li><li><strong>Review the read text</strong><p>The result shows the headline used and any detected source or date conflict.</p></li></ol></section></aside></div>}
@if (step === 'accepted' && accepted) {<section class="surface state-card"><span class="eyebrow">UPLOAD COMPLETE</span><div class="state-mark" aria-hidden="true">✓</div><h2>Your photo card was received</h2><p>The card is now queued for reading and source comparison. You do not need to keep this page open.</p>@if (previewUrl) {<img [src]="previewUrl" class="preview-image" alt="Submitted photocard">}<dl class="meta-grid"><div><dt>Comparing against</dt><dd>{{ claimedSourceName() }}</dd></div><div><dt>Scope</dt><dd>Headline only</dd></div></dl><div class="note">Keep the result link to follow progress and return later. If signed in, you can also use My Submissions.</div><div class="actions"><a class="btn btn-primary" [routerLink]="['/verify',accepted.submission_id]">View progress</a><a class="btn btn-secondary" routerLink="/history">My Submissions</a><button class="btn btn-ghost" (click)="reset()">Verify another card</button></div></section>}
</div></div>'''
p.write_text(out,encoding='utf-8'); p.with_suffix('.scss').write_text(':host { display: block; }\n',encoding='utf-8')
# Text and image preserves every field and its synchronous request.
p=root/'app/features/multimodal/multimodal.html'; s=p.read_text(encoding='utf-8-sig'); form=s[s.index('<form '):s.index('</form>')+7]
form=form.replace('<form (ngSubmit)="onSubmit()">','<form (ngSubmit)="onSubmit()"><fieldset [disabled]="loading">').replace('</form>','</fieldset></form>').replace('class="btn-submit"','class="btn btn-primary btn-full"').replace('Article Body Text','Bengali article text').replace('Article Image','Article image').replace('<label>Article image</label>','<label for="image">Article image</label>').replace('Verify Content','Check text and image').replace('Processing...','Checking text and image…').replace('alt="Preview"','alt="Selected article image"').replace('Enter news headline...','খবরের শিরোনাম লিখুন…').replace('Paste the full article text here...','খবরের সম্পূর্ণ লেখা এখানে দিন…')
out=header('CHECK TEXT & IMAGE','Read the story alongside its image.','Add the Bengali article and its accompanying image for a preliminary assessment. This method does not confirm publication by a particular news outlet.','MULTI')
out+='''@if (!result) {<div class="flow-grid"><section class="surface"><div class="section-heading"><span class="eyebrow">01 / ARTICLE &amp; IMAGE</span><h2>Add the news you received</h2><p>Headline, article text and image are all required.</p></div>'''+form+'''</section><aside class="side-stack">@if (loading) {<section class="surface status-panel" role="status"><span class="eyebrow">ASSESSMENT IN PROGRESS</span><div class="spinner"></div><h2>Checking the text and image</h2><p>Please keep this page open until the assessment is ready. No result has been reached yet.</p></section>} @else {<section class="surface"><span class="eyebrow">YOUR ARTICLE / PREVIEW</span><h2 class="claim-preview">{{ headline || 'Your headline will appear here' }}</h2>@if (previewUrl) {<img [src]="previewUrl" class="preview-image" alt="Selected article preview">}@if (bodyText) {<details><summary>Preview article text</summary><p class="preview-body">{{ bodyText }}</p></details>}<div class="note">The assessment considers the article text and image. The headline is retained as context for readers.</div></section>}<section class="context-panel"><h2>How to read this assessment</h2><p>The first finding is preliminary and can be wrong. Expert review is needed for a final decision.</p><p>For a comparison with a named news outlet and source links, use <a routerLink="/verify">news text verification</a>.</p></section></aside></div>}
@if (result && !loading) {<section class="flow-result"><div class="report-toolbar"><div><span class="eyebrow">ASSESSMENT READY</span><h2>Verification result</h2></div><button type="button" class="btn btn-secondary" (click)="result = null">Edit and check again</button></div><section class="surface"><span class="eyebrow">{{ result.expert_overall_verdict ? 'EXPERT REVIEW COMPLETE' : 'PRELIMINARY ASSESSMENT' }}</span><h2 class="assessment-value">{{ result.expert_overall_verdict ? overallVerdictLabel(result.expert_overall_verdict) : predictionLabel(result.prediction) }}</h2><p class="assessment-explanation">{{ result.expert_overall_verdict ? 'Expert review has finalized this claim. Open the saved result for its review status and the original submission.' : 'This is not a final verdict. The automated assessment can be wrong; expert review is still needed.' }}</p>@if (result.is_cached) {<p class="field-hint">A previous assessment of this content was reused.</p>}<div class="note">This assessment does not establish whether a particular news outlet published the article. No source comparison is provided by this method.</div><a [routerLink]="['/verify',result.submission_id]" class="btn btn-primary">Open full report ↗</a></section><section class="surface claim-section"><span class="eyebrow">SUBMITTED ARTICLE</span><h2 class="claim-preview">{{ headline }}</h2>@if (previewUrl) {<img [src]="previewUrl" class="preview-image" alt="Submitted article image">}<details><summary>Read submitted article text</summary><p class="long-text">{{ bodyText }}</p></details><p class="field-hint">Checked {{ formatDate(result.created_at) }}</p></section></section>}
</div></div>'''
p.write_text(out,encoding='utf-8'); p.with_suffix('.scss').write_text(':host { display: block; }\n',encoding='utf-8')
