"""
app/models/search_query.py
===========================
ORM model for the `search_queries` table.

Records every search query generated by Stage 3 and dispatched by Stage 4,
along with which provider executed it and how many results were returned.
This provides full audit trail of the retrieval process and is used for
debugging poor-retrieval failures.

Relationships:
    search_queries → verified_claims  (many-to-one)
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, Enum, ForeignKey, Index, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.constants import QueryType, SearchProvider
from app.models.base import Base, ReprMixin, UUIDMixin

if TYPE_CHECKING:
    from app.models.verified_claim import VerifiedClaim


class SearchQuery(UUIDMixin, ReprMixin, Base):
    """
    Records a single search query dispatched during Stage 3/4.

    Note: This model deliberately omits `TimestampMixin` and instead uses
    a single `executed_at` column, because search queries are write-once
    audit records that are never updated after creation.

    Attributes:
        claim_id:        FK to the parent verified_claim.
        query_type:      Category of query (headline, keywords, entities, etc.).
        query_text:      The exact query string sent to the search provider.
        search_provider: Which search backend executed this query.
        results_count:   Number of URLs returned (0 if provider returned nothing).
        executed_at:     Timestamp when the search was dispatched.
    """

    __tablename__ = "search_queries"

    # --- Core fields --------------------------------------------------------

    claim_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("verified_claims.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK to verified_claims — the claim this query was generated for",
    )

    query_type: Mapped[QueryType] = mapped_column(
        Enum(QueryType, name="query_type_enum", create_type=True),
        nullable=False,
        comment="Category of query: headline | keywords | entities | date_bound | body_summary",
    )

    query_text: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Exact query string sent to the search provider",
    )

    search_provider: Mapped[SearchProvider] = mapped_column(
        Enum(SearchProvider, name="search_provider_enum", create_type=True),
        nullable=False,
        index=True,
        comment="Which search provider executed this query: brave | google_rss | ddg",
    )

    results_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of result URLs returned by the provider",
    )

    executed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
        comment="Timestamp when the search query was dispatched (UTC)",
    )

    # --- Relationships ------------------------------------------------------

    claim: Mapped["VerifiedClaim"] = relationship(
        "VerifiedClaim",
        back_populates="search_queries",
        lazy="select",
    )

    # --- Composite indexes --------------------------------------------------

    __table_args__ = (
        Index("ix_search_queries_claim_provider", claim_id, search_provider),
        Index("ix_search_queries_claim_type", claim_id, query_type),
    )
