"""Generic revision file template for Alembic migrations.

Do not edit this file — it is used by `alembic revision` to generate
new migration scripts in the `versions/` directory.
"""
# revision identifiers, used by Alembic.
revision = 'f89542b9b55a'
down_revision = '3e7f64e4c47d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    op.execute("ALTER TYPE query_type_enum ADD VALUE IF NOT EXISTS 'SITE_RESTRICTED'")


def downgrade() -> None:
    pass # Postgres does not support removing values from an ENUM easily
