"""Generic revision file template for Alembic migrations.

Do not edit this file — it is used by `alembic revision` to generate
new migration scripts in the `versions/` directory.
"""
# revision identifiers, used by Alembic.
revision = 'be6f76179d91'
down_revision = 'seed_admin_user_001'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # Adding 'INTERNAL_SITE' to search_provider_enum enum type
    op.execute("ALTER TYPE search_provider_enum ADD VALUE IF NOT EXISTS 'INTERNAL_SITE'")

def downgrade() -> None:
    pass
