"""Generic revision file template for Alembic migrations.

Do not edit this file — it is used by `alembic revision` to generate
new migration scripts in the `versions/` directory.
"""
# revision identifiers, used by Alembic.
revision = '31eca564c430'
down_revision = 'c64e7a11f599'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # PostgreSQL 12+ supports ALTER TYPE ADD VALUE inside transactions.
    op.execute("ALTER TYPE search_provider_enum ADD VALUE IF NOT EXISTS 'SEARXNG'")


def downgrade() -> None:
    # Removing values from an enum in PostgreSQL is difficult and requires recreating the type.
    # For a downgrade, we typically leave the type alone or just pass.
    pass
